services:
  usersManagement:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: user_management
      POSTGRES_PASSWORD: user_management
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
 
volumes:
  pgdata: